export const tableData = [
  {
    eventName: "Cloud Innovation Summit",
    date: "2024-10-15",
    speaker: "Jane Doe",
    status: "Completed",
    attendees: 250,
    description: "Exploring the latest in cloud technologies.",
  },
  {
    eventName: "Blockchain Revolution Conference",
    date: "2024-11-05",
    speaker: "Dr. Peter Smith",
    status: "In Progress",
    attendees: 300,
    description: "Discussing blockchain's impact on industries.",
  },
  {
    eventName: "AI in Healthcare Symposium",
    date: "2024-12-01",
    speaker: "Dr. Aisha Malik",
    status: "Completed",
    attendees: 200,
    description: "Innovations in AI for improving healthcare.",
  },
  {
    eventName: "Future of Fintech Forum",
    date: "2024-10-25",
    speaker: "John Lee",
    status: "Completed",
    attendees: 220,
    description: "Insights into the future of financial technology.",
  },
  {
    eventName: "Data Analytics in Business",
    date: "2024-11-12",
    speaker: "Rachel Moore",
    status: "Completed",
    attendees: 180,
    description: "Using data analytics to drive business growth.",
  },
  {
    eventName: "Sustainable Energy Expo",
    date: "2024-09-28",
    speaker: "Prof. Alan Green",
    status: "Completed",
    attendees: 150,
    description: "Showcasing sustainable energy solutions.",
  },
  {
    eventName: "Web3 Interfaces Workshop",
    date: "2024-10-10",
    speaker: "Kevin Adams",
    status: "In Progress",
    attendees: 120,
    description: "Hands-on workshop on Web3 technologies.",
  },
  {
    eventName: "Global Marketing Summit",
    date: "2024-10-20",
    speaker: "Linda White",
    status: "Completed",
    attendees: 300,
    description: "Strategies for global marketing success.",
  },
  {
    eventName: "Cybersecurity Forum",
    date: "2024-10-30",
    speaker: "Dr. Amanda Clark",
    status: "In Progress",
    attendees: 210,
    description: "Exploring the latest in cybersecurity threats.",
  },
  {
    eventName: "SaaS Innovations Conference",
    date: "2024-11-01",
    speaker: "David Hughes",
    status: "Completed",
    attendees: 270,
    description: "Innovations in Software as a Service.",
  },
  {
    eventName: "GreenTech Symposium",
    date: "2024-10-12",
    speaker: "Anna Zhang",
    status: "Completed",
    attendees: 190,
    description: "Latest trends in green technologies.",
  },
  {
    eventName: "E-Commerce Future Workshop",
    date: "2024-10-05",
    speaker: "Chris Martin",
    status: "In Progress",
    attendees: 140,
    description: "Future trends in e-commerce.",
  },
  {
    eventName: "AI & Ethics Symposium",
    date: "2024-11-15",
    speaker: "Dr. Liam Patel",
    status: "In Progress",
    attendees: 160,
    description: "Debating the ethical implications of AI.",
  },
  {
    eventName: "Quantum Computing Summit",
    date: "2024-11-18",
    speaker: "Emily Wong",
    status: "Completed",
    attendees: 230,
    description: "The future of quantum computing.",
  },
  {
    eventName: "Healthcare Innovations Forum",
    date: "2024-12-10",
    speaker: "Sarah Johnson",
    status: "In Progress",
    attendees: 175,
    description: "Innovations in healthcare technologies.",
  },
  {
    eventName: "Virtual Reality Expo",
    date: "2024-10-02",
    speaker: "John Brown",
    status: "Completed",
    attendees: 300,
    description: "Exploring advancements in virtual reality.",
  },
  {
    eventName: "Digital Banking Conference",
    date: "2024-10-27",
    speaker: "Mark Wilson",
    status: "In Progress",
    attendees: 210,
    description: "Trends in digital banking solutions.",
  },
  {
    eventName: "Smart Cities Summit",
    date: "2024-11-20",
    speaker: "Jessica Taylor",
    status: "Completed",
    attendees: 190,
    description: "Innovations for smarter cities.",
  },
  {
    eventName: "Fintech Innovations Workshop",
    date: "2024-12-05",
    speaker: "Daniel Harris",
    status: "Completed",
    attendees: 220,
    description: "Workshops on the latest fintech innovations.",
  },
  {
    eventName: "Biotech Conference",
    date: "2024-09-29",
    speaker: "Susan Lee",
    status: "Completed",
    attendees: 180,
    description: "Discoveries in biotechnology.",
  },
  {
    eventName: "Robotics and AI Expo",
    date: "2024-12-02",
    speaker: "Paul Anderson",
    status: "In Progress",
    attendees: 240,
    description: "Exploring the intersection of robotics and AI.",
  },
  {
    eventName: "5G Future Summit",
    date: "2024-10-18",
    speaker: "Michael Young",
    status: "Completed",
    attendees: 200,
    description: "Discussing the future of 5G technology.",
  },
  {
    eventName: "AI-Powered Solutions Forum",
    date: "2024-11-25",
    speaker: "Sophia Green",
    status: "In Progress",
    attendees: 160,
    description: "Innovative AI solutions for business.",
  },
  {
    eventName: "Autonomous Vehicles Conference",
    date: "2024-10-13",
    speaker: "James Roberts",
    status: "Completed",
    attendees: 180,
    description: "The latest in autonomous vehicle technology.",
  },
  {
    eventName: "Digital Transformation Workshop",
    date: "2024-10-04",
    speaker: "Natalie Hall",
    status: "In Progress",
    attendees: 150,
    description: "Transforming businesses in the digital age.",
  },
  {
    eventName: "Clean Energy Expo",
    date: "2024-09-30",
    speaker: "Laura Thomas",
    status: "Completed",
    attendees: 200,
    description: "Showcasing clean energy technologies.",
  },
  {
    eventName: "Cloud Computing Summit",
    date: "2024-12-08",
    speaker: "Edward Scott",
    status: "In Progress",
    attendees: 170,
    description: "Exploring advancements in cloud computing.",
  },
  {
    eventName: "Big Data Analytics Workshop",
    date: "2024-11-30",
    speaker: "Maria Martinez",
    status: "Completed",
    attendees: 190,
    description: "Hands-on big data analytics training.",
  },
  {
    eventName: "Sustainable Business Forum",
    date: "2024-12-12",
    speaker: "Richard Davis",
    status: "In Progress",
    attendees: 165,
    description: "Sustainable practices for modern businesses.",
  },
  {
    eventName: "Future of AI Conference",
    date: "2024-10-06",
    speaker: "Catherine King",
    status: "Completed",
    attendees: 230,
    description: "The future trajectory of AI technologies.",
  },
  {
    eventName: "Machine Learning Expo",
    date: "2024-11-22",
    speaker: "Matthew Clark",
    status: "In Progress",
    attendees: 180,
    description: "Exploring machine learning applications.",
  },
  {
    eventName: "Blockchain Summit",
    date: "2024-10-08",
    speaker: "Christine Lewis",
    status: "Completed",
    attendees: 250,
    description: "Deep dive into blockchain technologies.",
  },
  {
    eventName: "Digital Health Innovations",
    date: "2024-10-22",
    speaker: "Henry Thompson",
    status: "In Progress",
    attendees: 160,
    description: "Innovations in digital health solutions.",
  },
  {
    eventName: "Virtual Workplace Strategies",
    date: "2024-11-10",
    speaker: "Ella Robinson",
    status: "Completed",
    attendees: 210,
    description: "Optimizing remote work environments.",
  },
  {
    eventName: "Artificial Intelligence Conference",
    date: "2024-11-15",
    speaker: "Tom White",
    status: "In Progress",
    attendees: 220,
    description: "Latest trends in artificial intelligence.",
  },
  {
    eventName: "Fintech Disruption Forum",
    date: "2024-12-03",
    speaker: "Olivia Martin",
    status: "Completed",
    attendees: 200,
    description: "Discussing disruptive innovations in fintech.",
  },
  {
    eventName: "Ethical AI Conference",
    date: "2024-10-14",
    speaker: "Lucas Hall",
    status: "In Progress",
    attendees: 180,
    description: "Exploring ethical considerations in AI.",
  },
  {
    eventName: "Smart Home Technologies Expo",
    date: "2024-11-02",
    speaker: "Nancy Smith",
    status: "Completed",
    attendees: 190,
    description: "The latest in smart home innovations.",
  },
  {
    eventName: "AgriTech Innovations Forum",
    date: "2024-11-28",
    speaker: "Henry Garcia",
    status: "In Progress",
    attendees: 175,
    description: "Innovative technologies in agriculture.",
  },
  {
    eventName: "Healthcare Data Summit",
    date: "2024-12-07",
    speaker: "Chloe Wilson",
    status: "Completed",
    attendees: 210,
    description: "Harnessing data in healthcare.",
  },
  {
    eventName: "Mobile App Development Workshop",
    date: "2024-11-14",
    speaker: "Kevin Nguyen",
    status: "In Progress",
    attendees: 160,
    description: "Hands-on workshop for mobile app development.",
  },
  {
    eventName: "Supply Chain Innovations Summit",
    date: "2024-12-04",
    speaker: "Julia Evans",
    status: "Completed",
    attendees: 200,
    description: "Innovative practices in supply chain management.",
  },
  {
    eventName: "Tech Innovations Showcase",
    date: "2024-12-15",
    speaker: "Alice Green",
    status: "Completed",
    attendees: 250,
    description: "Showcasing the latest in technology innovations.",
  },
  {
    eventName: "Virtual Reality for Education",
    date: "2024-11-29",
    speaker: "Martin King",
    status: "In Progress",
    attendees: 175,
    description: "Exploring the use of VR in educational settings.",
  },
  {
    eventName: "Digital Marketing Strategies",
    date: "2024-10-21",
    speaker: "Sophia Chen",
    status: "Completed",
    attendees: 300,
    description: "Effective strategies for digital marketing success.",
  },
  {
    eventName: "IoT Security Conference",
    date: "2024-11-08",
    speaker: "Oliver Brown",
    status: "In Progress",
    attendees: 180,
    description: "Addressing security challenges in IoT.",
  },
  {
    eventName: "Artificial Intelligence in Finance",
    date: "2024-11-25",
    speaker: "Emily Carter",
    status: "Completed",
    attendees: 220,
    description: "AI applications in financial services.",
  },
  {
    eventName: "Future of Work Summit",
    date: "2024-12-18",
    speaker: "James Wilson",
    status: "In Progress",
    attendees: 200,
    description: "Discussing the evolution of work environments.",
  },
  {
    eventName: "Innovations in Cybersecurity",
    date: "2024-10-15",
    speaker: "Karen Hall",
    status: "Completed",
    attendees: 190,
    description: "Latest innovations in cybersecurity measures.",
  },
  {
    eventName: "Sustainable Agriculture Conference",
    date: "2024-12-05",
    speaker: "Michael Green",
    status: "In Progress",
    attendees: 170,
    description: "Promoting sustainable practices in agriculture.",
  },
  {
    eventName: "Advanced Robotics Workshop",
    date: "2024-11-12",
    speaker: "Linda Taylor",
    status: "Completed",
    attendees: 230,
    description: "Hands-on workshop on robotics advancements.",
  },
  {
    eventName: "Health Tech Innovations Forum",
    date: "2024-10-29",
    speaker: "David Lewis",
    status: "In Progress",
    attendees: 160,
    description: "Innovations at the intersection of health and technology.",
  },
  {
    eventName: "Smart Transportation Summit",
    date: "2024-11-30",
    speaker: "Nina White",
    status: "Completed",
    attendees: 240,
    description: "Exploring innovations in transportation systems.",
  },
  {
    eventName: "Women in Tech Conference",
    date: "2024-12-20",
    speaker: "Rachel Johnson",
    status: "In Progress",
    attendees: 250,
    description: "Celebrating women leading in technology.",
  },
  {
    eventName: "Future of Energy Symposium",
    date: "2024-11-05",
    speaker: "Henry Black",
    status: "Completed",
    attendees: 210,
    description: "Discussing future energy solutions.",
  },
  {
    eventName: "Blockchain Applications Workshop",
    date: "2024-10-30",
    speaker: "Catherine Lee",
    status: "In Progress",
    attendees: 180,
    description: "Hands-on workshop exploring blockchain use cases.",
  },
  {
    eventName: "Cloud Security Summit",
    date: "2024-12-02",
    speaker: "Paul King",
    status: "Completed",
    attendees: 190,
    description: "Addressing security in cloud environments.",
  },
  {
    eventName: "Creative AI Solutions Forum",
    date: "2024-11-14",
    speaker: "Julia Martinez",
    status: "In Progress",
    attendees: 175,
    description: "Innovative applications of AI in creative fields.",
  },
  {
    eventName: "Next-Gen Database Technologies",
    date: "2024-10-19",
    speaker: "Chris Clark",
    status: "Completed",
    attendees: 220,
    description: "Exploring advancements in database technologies.",
  },
  {
    eventName: "Blockchain Applications Workshop",
    date: "2024-10-30",
    speaker: "Catherine Lee",
    status: "In Progress",
    attendees: 180,
    description: "Hands-on workshop exploring blockchain use cases.",
  },
  {
    eventName: "Cloud Security Summit",
    date: "2024-12-02",
    speaker: "Paul King",
    status: "Completed",
    attendees: 190,
    description: "Addressing security in cloud environments.",
  },
  {
    eventName: "Artificial Intelligence Conference",
    date: "2024-11-15",
    speaker: "Tom White",
    status: "In Progress",
    attendees: 220,
    description: "Latest trends in artificial intelligence.",
  },
  {
    eventName: "Fintech Disruption Forum",
    date: "2024-12-03",
    speaker: "Olivia Martin",
    status: "Completed",
    attendees: 200,
    description: "Discussing disruptive innovations in fintech.",
  },
  {
    eventName: "Ethical AI Conference",
    date: "2024-10-14",
    speaker: "Lucas Hall",
    status: "In Progress",
    attendees: 180,
    description: "Exploring ethical considerations in AI.",
  },
  {
    eventName: "Smart Home Technologies Expo",
    date: "2024-11-02",
    speaker: "Nancy Smith",
    status: "Completed",
    attendees: 190,
    description: "The latest in smart home innovations.",
  },
  {
    eventName: "AgriTech Innovations Forum",
    date: "2024-11-28",
    speaker: "Henry Garcia",
    status: "In Progress",
    attendees: 175,
    description: "Innovative technologies in agriculture.",
  },
  {
    eventName: "Healthcare Data Summit",
    date: "2024-12-07",
    speaker: "Chloe Wilson",
    status: "Completed",
    attendees: 210,
    description: "Harnessing data in healthcare.",
  },
  {
    eventName: "Mobile App Development Workshop",
    date: "2024-11-14",
    speaker: "Kevin Nguyen",
    status: "In Progress",
    attendees: 160,
    description: "Hands-on workshop for mobile app development.",
  },
  {
    eventName: "Supply Chain Innovations Summit",
    date: "2024-12-04",
    speaker: "Julia Evans",
    status: "Completed",
    attendees: 200,
    description: "Innovative practices in supply chain management.",
  },
  {
    eventName: "Tech Innovations Showcase",
    date: "2024-12-15",
    speaker: "Alice Green",
    status: "Completed",
    attendees: 250,
    description: "Showcasing the latest in technology innovations.",
  },
];
